// <auto-generated />
namespace Fire2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class newstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newstable));
        
        string IMigrationMetadata.Id
        {
            get { return "202506230422051_newstable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
